openapiOptions:
  file:
    - file: paymentspb/messages.proto
      option:
        info:
          title: Payments API
          version: "1.0.0"
        basePath: /
  method:
    - method: paymentspb.PaymentsService.GetPayments
      option:
        operationId: getPayments
        tags:
          - Payment
        summary: get Payment list
    - method: paymentspb.PaymentsService.AuthorizePayment
      option:
        operationId: authorizePayment
        tags:
          - Payment
        summary: Authorize a future payment
    - method: paymentspb.PaymentsService.CreateInvoice
      option:
        operationId: createInvoice
        tags:
          - Invoice
        summary: Create an invoice for payment
    - method: paymentspb.PaymentsService.PayInvoice
      option:
        operationId: payInvoice
        tags:
          - Invoice
        summary: Pay an invoice
    - method: paymentspb.PaymentsService.GetInvoices
      option:
        operationId: getInvoices
        tags:
          - Invoice
        summary: get invoice list
    
